apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  labels:
    app: spring-boot-mysql
spec:
  template:
    metadata:
      labels:
        app: spring-boot-mysql
    spec:
      containers:
        - image: mohamednabiel717/spring-boot
          name: spring-boot-container
          ports:
            - containerPort: 8080
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database-name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user-password
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-mysql
