apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: spring-boot-mysql
spec:
  type: NodePort
  ports:
    - targetPort: 3306
      port: 80
      nodePort: 3306
  selector:
    app: spring-boot-mysql
    tier: mysql
