version: '3'
services:
  capiter-mysql:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=springboot_mysql_example
    ports:
      - "3306:3306"
  springboot-docker-container:
    image: springboot-docker-container
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://capiter-mysql:3306/springboot_mysql_example
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "YOUR_DB_PASSWORD"
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - capiter-mysql
